/**
 * generatedDoc.ts — the two mechanisms a committed measurement needs so it cannot rot,
 * extracted at their SECOND use (#1270, after #1046).
 *
 * This boundary has now produced the same defect seven times: a figure measured once,
 * typed into a document, and left there while the corpus, the writers or the instrument
 * moved underneath it. #1046 fixed one table and the fix decomposed into exactly two
 * reusable pieces, which is what justifies pulling them out here rather than at the first
 * use — one instance is a function, two is a module.
 *
 * **1. GENERATE, DO NOT TRANSCRIBE.** A section that reports numbers is spliced between
 * markers on every run, so it cannot disagree with the run. Nothing asserts the spliced
 * text: a test that writes a file and then checks it is circular, and there is nothing
 * left for an assertion to catch. What CAN still fail is the splice silently doing
 * nothing, which is the same class as the defect it replaces — an anchored edit whose
 * anchor has gone appends instead, and every count-the-token check still passes
 * ([[P497]]). So the splice throws on a missing, duplicated or inverted marker.
 *
 * **2. AN OBSERVATION THAT NO GATE CAN RE-TAKE NEEDS AN EXPIRY.** Some figures are only
 * obtainable by rewriting a module constant and running again — the roll's period cap is
 * the standing example, and those are exactly the figures that rot, because nothing
 * re-derives them. Deriving them by arithmetic instead is the same defect inverted. The
 * treatment is to record, in the SAME run, a companion reading that every gate re-takes
 * for free, and to compare that. When the companion stops matching, the observation is
 * stale and the gate says so.
 *
 * ⚠ STATED LIMIT, and it travels with the mechanism: the companion is a NECESSARY
 * condition, not a sufficient one. A change that moves only the observed reading — for a
 * cap sweep, one touching only the band between the shipped and candidate values — leaves
 * the companion identical and this check green. It is strictly better than the nothing
 * these figures had before, and it is not proof of currency. Re-take the observation
 * whenever the mechanism the constant governs changes, green or not.
 */

export interface BlockMarkers {
  begin: string
  end: string
}

/**
 * The marker pair for a generated section, named so one document can carry several.
 *
 * `by` names the generator in the marker itself, because a reader who finds a stale-looking
 * block needs to know which run produces it before they can decide whether it is stale.
 */
export function blockMarkers(name: string, issue: string, by = 'writer-census.test.ts'): BlockMarkers {
  return {
    begin: `<!-- ${name}:BEGIN — generated by ${by} (${issue}); do not edit by hand -->`,
    end: `<!-- ${name}:END -->`,
  }
}

/**
 * Splice `body` between the markers.
 *
 * THROWS rather than returning the source unchanged, because "the generator quietly
 * stopped generating" and "the generator ran" must not read the same.
 */
export function writeGeneratedBlock(
  source: string,
  body: string,
  m: BlockMarkers,
  where: string,
): string {
  const i = source.indexOf(m.begin)
  const j = source.indexOf(m.end)
  if (i < 0) throw new Error(`${where}: the generated block's BEGIN marker is gone — nothing would be written`)
  if (j < 0) throw new Error(`${where}: the generated block's END marker is gone — nothing would be written`)
  if (j < i) throw new Error(`${where}: the generated block's markers are inverted`)
  if (source.indexOf(m.begin, i + 1) >= 0)
    throw new Error(`${where}: the generated block's BEGIN marker appears twice — the splice is ambiguous`)
  return source.slice(0, i + m.begin.length) + '\n\n' + body + '\n\n' + source.slice(j)
}

/**
 * Every numeric field on which two readings disagree, as `path expected -> actual`.
 *
 * Walks the shape rather than naming fields, so a reading that gains a column is compared
 * on it automatically. A field present in one side and absent in the other is reported
 * too — a silently dropped column is how a comparison starts passing for the wrong reason.
 */
export function readingDrift(expected: unknown, actual: unknown, prefix = ''): string[] {
  if (typeof expected === 'number' || typeof actual === 'number')
    return expected === actual ? [] : [`${prefix} ${expected} -> ${actual}`]
  if (
    typeof expected !== 'object' || expected === null ||
    typeof actual !== 'object' || actual === null
  )
    return expected === actual ? [] : [`${prefix} ${JSON.stringify(expected)} -> ${JSON.stringify(actual)}`]

  const e = expected as Record<string, unknown>
  const a = actual as Record<string, unknown>
  const keys = [...new Set([...Object.keys(e), ...Object.keys(a)])].sort()
  return keys.flatMap((k) => {
    const at = prefix ? `${prefix}.${k}` : k
    if (!(k in e)) return [`${at} (absent) -> ${JSON.stringify(a[k])}`]
    if (!(k in a)) return [`${at} ${JSON.stringify(e[k])} -> (absent)`]
    return readingDrift(e[k], a[k], at)
  })
}

/**
 * Is a committed observation still about this tree?
 *
 * Throws with the script to re-take it rather than returning a boolean, because the only
 * useful thing a caller can do with `false` is say exactly this — and says why editing
 * the number instead is not a repair.
 */
export function assertCompanionCurrent(opts: {
  /** what is being guarded, for the message: "the cap-12 P6 observation" */
  what: string
  /** the command that re-takes it */
  script: string
  /** the reading recorded alongside the observation, at a cap every gate re-takes */
  companion: unknown
  /** that same reading, taken now */
  live: unknown
}): void {
  const drift = readingDrift(opts.companion, opts.live)
  if (!drift.length) return
  throw new Error(
    `${opts.what} is STALE — the world it was taken in has moved:\n` +
      drift.map((s) => `    ${s}`).join('\n') +
      `\n  Re-take it:  ${opts.script}\n` +
      `  It cannot be repaired by editing the number: that reading is an OBSERVATION, and ` +
      `deriving it by arithmetic is the defect this check exists to prevent.`,
  )
}
