/**
 * mini-corpus.test.ts — the notation parsers, gated against what people ACTUALLY write.
 *
 * 1633 distinct mini strings harvested from 360 real public Bakery tunes
 * (`mini-corpus.json`, regenerated by `_harvest-mini-corpus.spec.ts`). For
 * each, both view parsers are asked for a verdict, and the whole verdict set is
 * snapshotted. Any change to the grammar that changes ANY verdict on real-world
 * input shows up as a reviewable diff.
 *
 * WHY THIS EXISTS — a specific failure, not a principle.
 *
 * Swapping the hand-rolled mini grammar for Strudel's own krill parser (#903)
 * recovered 28 units and silently broke ONE: `[c4,e4,g4,c5]*2`, a chord with a
 * multiplier, stopped opening. Nothing caught it.
 *   - The 201 notation unit tests didn't: they cover the subset by hand, and
 *     nobody had thought to hand-write a chord with a multiplier.
 *   - `edit-parity.test.ts` didn't: the 57 curated fixtures contained no such
 *     shape. It was GREEN against the real regression until the fixture was
 *     added by hand, after the fact.
 *   - The swept coverage % didn't: it read "+32", which was +33 gained and −1
 *     LOST. An aggregate NETS a regression against a recovery, so the single
 *     number everyone quotes is exactly the number that hides this.
 * It was caught by diffing verdicts over ~1500 real strings — in a throwaway
 * script, deleted the same day. This file is that script, kept.
 *
 * Curated fixtures encode what we thought to write down. This encodes what
 * people wrote. The two catch different things, so the gate keeps both.
 *
 * WHAT THE SNAPSHOT IS FOR. It is not a correctness oracle — it cannot be. It
 * records what the parsers CURRENTLY decide about real input, so that a change
 * to that decision must be looked at by a human. Both directions matter:
 *   - `ok -> refused`  a regression: something editable stopped opening
 *   - `refused -> ok`  a WIDENING: the view now claims it can show something it
 *                      previously declined. That is a real decision (does the
 *                      writer round-trip it, or will it silently flatten the
 *                      user's notation on first edit?) and must be deliberate.
 *   - reason changes   the refusal's CAUSE moved — often the honest news, e.g.
 *                      "beyond the editable subset" resolving into a named
 *                      feature.
 *
 * DRIFT POLICY — the same as `parity.test.ts`, and it is the whole point:
 * **the diff IS the news.** A PR touching the notation path that moves this
 * snapshot must explain each line in its body. NEVER run `vitest -u` to make it
 * green: this file exists precisely because a silent verdict change shipped
 * once, and regenerating without reading re-buckets exactly that as an
 * improvement.
 *
 * COVERAGE LIMITS, stated so nobody over-trusts a green run. This paragraph has
 * been wrong twice — it kept describing a regex two rules ago — so it now says
 * what the harvest CURRENTLY does and names the file that decides it.
 *
 * The corpus is the UNION of two proposers (#1242, `_harvest-mini-corpus.spec.ts`):
 *   - LITERAL: the first argument of `s`/`sound`/`note`/`n`, taken from the AST.
 *     Backticks ARE included (#1037 — they are how people write multi-cycle
 *     patterns, and excluding them biased the corpus away from the material the
 *     readers are weakest on). Single quotes are not, because the transpiler does
 *     not reify them.
 *   - UNIT: the note content the PRODUCT resolves for each unit the panel routes
 *     to a notation surface — bound references, chained arguments, root literals
 *     and non-content heads, all of which the literal walk is blind to.
 *
 * Still outside the net: a mini in a later argument that no unit resolves to
 * (`.struct("x*4")` on its own), and interpolated templates. Real forms exist
 * outside it — measured, not assumed.
 */
import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

// Deep source path, not the `@stave/editor` barrel: the barrel pulls
// @strudel/draw -> gifenc (CJS) and crashes the ESM resolver under vite-node.
// Same convention as parity.test.ts:38.
import {
  parseStepGrid,
  parsePianoRoll,
} from '../../../editor/src/visualEdit/notation/parse'

const corpusDir = path.dirname(fileURLToPath(import.meta.url))

interface Corpus {
  distinctTunes: number
  distinct: number
  /** how many strings each proposer contributed — see the floor below */
  via: { literal: number; unit: number; both: number }
  minis: { mini: string; tunes: number; via: 'literal' | 'unit' | 'both' }[]
}

const corpus: Corpus = JSON.parse(
  fs.readFileSync(path.join(corpusDir, 'mini-corpus.json'), 'utf8'),
)

/** one parser's verdict: `ok`, or the reason it declined */
const verdict = (r: { ok: boolean; reason?: string }): string =>
  r.ok ? 'ok' : (r.reason ?? '(no reason)')

describe('mini-corpus — real-world mini strings', () => {
  it('the corpus is present and substantial (a gate over 3 strings is not a gate)', () => {
    expect(corpus.minis.length).toBeGreaterThan(1000)
    expect(corpus.distinctTunes).toBeGreaterThan(300)
    expect(corpus.distinct).toBe(corpus.minis.length)
  })

  /**
   * BOTH PROPOSERS MUST HAVE ANSWERED (#1242).
   *
   * The harvest is a union: a literal walk over `s`/`sound`/`note`/`n`, and the
   * product's own unit walk through the resolver #1240 wired. Either one can go
   * dark without the corpus looking wrong — drop the unit proposer and the file
   * still holds 1538 strings, sails past the 1000 floor above, and every gate
   * downstream stays green over a population that silently lost the whole
   * feature. That is the shape #1242 was filed for, one level up: a green gate
   * whose scope excludes the new work reads exactly like one that covered it.
   *
   * So the floor is on the SLICE, not the total, and it is set from the observed
   * value with a little slack rather than at equality — a refresh that legitimately
   * gains strings must not redden ([[P541]]).
   *
   *   MEASURED 2026-08-14 over 360 tunes: literal 433 · unit 95 · both 1105.
   *   `unit + both` = 1200 is the population the resolver reaches;
   *   `unit` = 95 is the slice NO literal rule can see, and is the one at risk.
   */
  it('both harvest proposers contributed (a union with one dead half looks healthy)', () => {
    const tally = corpus.minis.reduce(
      (acc, m) => ({ ...acc, [m.via]: (acc[m.via] ?? 0) + 1 }),
      {} as Record<string, number>,
    )
    // The header's tally and a recount over the rows must AGREE — a single
    // reading cannot tell a dead proposer from a mis-summed header.
    expect(tally).toEqual(corpus.via)
    expect(corpus.via.unit, 'the resolver-only slice is empty').toBeGreaterThan(80)
    expect(corpus.via.literal, 'the literal slice is empty').toBeGreaterThan(400)
    expect(corpus.via.both).toBeGreaterThan(1000)
  })

  /**
   * The load-bearing assertion. Every mini, both parsers, verdict pinned.
   * Ordered by the corpus's own sorted order so the diff is readable.
   *
   * ⚠ 10 GRID VERDICTS FLIPPED `ok` → a refusal at #1010 P4c, and no roll verdict moved.
   * The printer now preserves a note's length, so prove-before-offer (`parse.ts:1638`)
   * stops offering a grid for units whose length the column resolution cannot spell:
   * 8 land on "a played note has no source token of its own to edit" and 2 on "nothing in
   * this view could be edited on its own". Every one is a view that could previously be
   * opened and then mis-written — the ranking that decides it is older than this phase
   * (`roll-cap-sweep.test.ts`: a derived view that mis-writes is worse than no view).
   *
   * READ, NOT REGENERATED-PAST. The corpus input is byte-identical in this change, so the
   * code was the only variable and the diff was checkable by construction ([[P361]]):
   * `_p4c-pin-attribution.spec.ts` derives the set from base-vs-HEAD parse and asserts
   * that this snapshot moved on exactly it, that every flip is `ok` → refusal and never
   * the reverse, and that the round-trip lock lost the same 10 while its
   * `serializer-null` pin gained nothing.
   */
  it('pins every grid + roll verdict over the real-world corpus', () => {
    const verdicts = corpus.minis.map(({ mini }) => ({
      mini,
      grid: verdict(parseStepGrid(mini)),
      roll: verdict(parsePianoRoll(mini)),
    }))
    expect(verdicts).toMatchSnapshot('real-world-verdicts')
  })

  /**
   * The summary the snapshot cannot give at a glance: how much of real input
   * each view opens. A floor, not an equality — an honest widening must not
   * trip it, but a collapse must. The precise instrument is the snapshot above;
   * this is the blunt one that fails loudly if the parser starts throwing.
   */
  it('keeps a real-world open-rate floor', () => {
    const openable = corpus.minis.filter(
      ({ mini }) => parseStepGrid(mini).ok || parsePianoRoll(mini).ok,
    ).length
    // MEASURED 2026-07-17 over these 1500 strings, by running it — not
    // remembered, and not copied from a summary:
    //   grid opens   781/1500 (52.1%)
    //   roll opens   392/1500 (26.1%)
    //   either       975/1500 (65.0%)
    // The floor is deliberately slack (50%): this test's job is to fail loudly
    // if the parsers collapse, while the SNAPSHOT above catches the single-unit
    // movements. A tight floor here would just duplicate the snapshot and go
    // red on every honest refresh.
    expect(openable).toBeGreaterThan(corpus.minis.length * 0.5)
  })

  /**
   * A parser must never THROW on real input — a refusal is a verdict, a crash
   * takes the panel down with it. krill throws on malformed mini (a lone `_`,
   * unbalanced brackets) and the adapter is responsible for catching that and
   * returning `{ ok: false }`. This asserts that responsibility over every real
   * string rather than trusting the try/catch by inspection.
   */
  it('never throws on real input — a refusal is a verdict, a crash is not', () => {
    const threw: string[] = []
    for (const { mini } of corpus.minis) {
      try {
        parseStepGrid(mini)
        parsePianoRoll(mini)
      } catch (e) {
        threw.push(`${JSON.stringify(mini)} -> ${(e as Error).message}`)
      }
    }
    expect(threw).toEqual([])
  })
})
